config/routes.rb
Rails.application.routes.draw do

  # archive
  resources :posts
  controller :posts do
    post "markdown"
  end

  controller :posts do
    get "archive", as: "archive"
  end

  # sessions
  resources :sessions, only: [:new, :create]
  controller :sessions do
    get "destroy", as: "logout"
  end

  resources :projects, except: [:show]
  controller :projects do
    get "portfolio", action: :index
  end

  resources :logins, except: [:show]

  # root
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/login.rb
class Login < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :username, length: { minimum: 2 }
  validates :password, length: { minimum: 8 }
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  has_one_attached :image

  extend FriendlyId
  friendly_id :name, use: :slugged

  # validation
  validates :title, :contents, :slug, presence: true
  validates :slug, uniqueness: true
  validates_format_of :slug, with: /\A[a-z0-9-]+\z/

  scope :tag, ->(name) { joins(:tags).where(tags: { name: name }) }

  def generate_markdown_html
    renderer = Redcarpet::Render::HTML.new(prettify: true)
    Redcarpet::Markdown.new(renderer, fenced_code_blocks: true).render(contents)
  end

  def date_line
    line = "posted " + created_at.localtime.strftime("%b %e %Y")
    line += ", last updated " + last_updated.strftime("%b %e %Y") if last_updated
    line
  end

  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    tags.map(&:name).join(", ")
  end
end

app/models/project.rb
class Project < ApplicationRecord
  has_one_attached :image

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings
  validates :name, presence: true, uniqueness: true

  scope :with_content, -> { select { |t| Post.tag(t.name).any? }.uniq }
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authorize

  include ApplicationHelper

  private

  def authorize
    return if authenticated?
    redirect_to new_session_url, method: :delete, notice: "Please log in"
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:update, :destroy]
  respond_to :html

  def create
    @login = Login.new(login_params)
    @login.save
    respond_with @login, location: posts_url
  end

  def update
    if @login.update(login_params)
      respond_with @login, location: root_path
    else
      respond_to do |format|
        format.html { render plain: "Failed." }
      end
    end
  end

  def destroy
    @login.destroy
    respond_with @login
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_login
    @login = Login.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def login_params
    params.require(:login).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:index, :show]
  respond_to :html
  responders :flash

  def index
    @posts = Post.includes(:tags)
                 .distinct
                 .order(created_at: :desc)
                 .where(published: true)
                 .page(params[:page])
                 .per(10)

    if params[:tag]
      @posts = @posts.tag(params[:tag])
      @tag = params[:tag]
    end

    respond_with @posts
  end

  def archive
    @posts = Post.order(created_at: :desc)
    respond_with @posts
  end

  def show
  end

  def markdown
    content = request.body.read

    renderer = Redcarpet::Render::HTML.new(prettify: true)
    markdown = Redcarpet::Markdown.new(renderer, fenced_code_blocks: true)
    render json: { content: markdown.render(content) }
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.save
    respond_with @post
  end

  def update
    @post.update(post_params)
    respond_with @post
  end

  def destroy
    @post.destroy
    respond_with @post
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:title, :slug, :contents, :published, :all_tags, :last_updated, :image)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy]
  skip_before_action :authorize, only: [:index]
  respond_to :html
  responders :flash

  # GET /projects
  def index
    @projects = Project.all

    respond_with @projects
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)
    @project.save
    respond_with @project, location: projects_path
  end

  # PATCH/PUT /projects/1
  def update
    @project.update(project_params)
    respond_with @project
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    respond_with @project
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def project_params
    params.require(:project).permit(:name, :url, :description, :image)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize

  def new
    if !session[:login_id].blank? && Login.where(id: session[:login_id]).any?
      redirect_to posts_url
    else
      session[:login_id] = nil
    end
  end

  def create
    session[:login_id] = nil
    login = Login.find_by(username: params[:username].strip)
    if login&.authenticate(params[:password].strip)
      session[:login_id] = login.id
      redirect_to posts_url
    else
      redirect_to new_session_url, alert: "Invalid login/password combination"
    end
  end

  def destroy
    session[:login_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include ActionView::Helpers::NumberHelper

  def title(page_title)
    content_for(:title) { "#{page_title} - Taylor Thurlow" }
  end

  def current_user
    return Login.find(session[:login_id]) if session[:login_id]
    return nil
  end

  def authenticated?
    return !session[:login_id].blank? && Login.where(id: session[:login_id]).any?
  end
end

app/views/application/_favicon.html.erb
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'favicon/apple-touch-icon.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon/favicon-16x16.png' %>">
<link rel="manifest" href="<%= asset_path 'favicon/site.webmanifest' %>">
<link rel="mask-icon" href="<%= asset_path 'favicon/safari-pinned-tab.svg' %>" color="#5bbad5">
<link rel="shortcut icon" href="<%= asset_path 'favicon/favicon.ico' %>">
<meta name="apple-mobile-web-app-title" content="Taylor Thurlow">
<meta name="application-name" content="Taylor Thurlow">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="msapplication-config" content="<%= asset_path 'favicon/browserconfig.xml' %>">
<meta name="theme-color" content="#ffffff">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : 'Taylor Thurlow' %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= render 'application/favicon' %>

    <%= stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "prettify_tomorrow_night", media: "all", "data-turbolinks-track" => true %>
    <meta name="google-site-verification" content="AyBIEFPOS1aXznunaI8SoQV9VjUr8LgiK69PBYLJ5Lo" />
  </head>
  <body>
    <div id="container">
      <div id="sidebar">
        <div>
          <%= link_to image_tag('logo-768.png', class: 'logo', size: '128'), root_url %>
          <div id="sidebar-name">Taylor Thurlow</div>
          <div id="sidebar-tagline">web developer, rubyist</div>
          <div id="sidebar-social">
            <div class="social-link"><%= link_to 'GitHub', 'https://github.com/taylorthurlow' %></div>
            <div class="social-link-separator">-</div>
            <div class="social-link"><%= link_to 'Projects', projects_path %></div>
            <div class="social-link-separator">-</div>
            <div class="social-link"><%= link_to 'Résumé', '/files/resume.pdf' %></div>
          </div>
        </div>

        <div id="sidebar-footer">
          <p><%= link_to "&copy;".html_safe, new_session_url %><%= Time.now.year %> Taylor Thurlow</p>
          <% if authenticated? %>
            <p>
              <%= link_to '', new_post_path, class: "fa fa-pencil" %>
              <%= link_to '', archive_path, class: "fa fa-history" %>
              <%= link_to '', logout_path, class: "fa fa-sign-out" %>
            </p>
          <% end %>
        </div>
      </div>
      <div id="content">
        <% if notice %>
          <p id="notice"><%= notice %></p>
        <% end %>

        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, placeholder: 'title' %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :published %>
    <%= f.check_box :published %>
  </div>

  <% if @post.new_record? %>
    <div class="field">
      <%= f.text_field :slug, placeholder: 'slug' %>
    </div>
  <% end %>

  <div class="field">
    <%= f.date_field :last_updated, min: @post.created_at&.strftime('%Y-%M-%D') %>
  </div>

  <div class="field">
    <%= f.text_field :all_tags, placeholder: 'tags' %>
  </div>

  <div class="field monospace">
    <%= f.text_area :contents, placeholder: 'Post body (accepts markdown)', id: 'content_text' %>
  </div>

  <div class="actions">
    <%= f.submit %>
    <%= button_tag 'Preview', type: 'button', onclick: 'markdownPreview()' %>
  </div>
<% end %>

<div class="post_preview"></div>

<script>
  function markdownPreview() {
    var request = new XMLHttpRequest();
    var raw = document.querySelectorAll("#content_text")[0].value;
    request.open("POST", "/markdown", true);
    request.setRequestHeader("Content-Type", "text/plain; charset=UTF-8");
    var csrfToken = document.querySelectorAll('meta[name="csrf-token"]')[0].content;
    request.setRequestHeader('X-CSRF-Token', csrfToken);

    request.onload = function() {
      if (request.status >= 200 && request.status < 300) {
        var markdown = JSON.parse(request.responseText).content;
        document.querySelectorAll(".post_preview")[0].innerHTML = '<div class="blog_post"><div class="blog_post_contents">' + markdown + '</div></div>'
        PR.prettyPrint();
      }
    };

    request.onerror = function() {
      console.error("There was a problem sending the markdown render request.");
    };

    request.send(raw);
  };
</script>

app/views/posts/_post.erb
<div class="blog_post">
  <h1 class="blog_post_title"><%= link_to post.title, post_url(post) %></h1>
  <div class="blog_post_date_line"><h3><%= post.date_line %></h3></div>
  <% if is_authenticated? %>
    <ul>
      <li><%= link_to '', edit_post_url(post), class: "fa fa-pencil" %></li>
      <li><%= link_to '', post_url(post), method: :delete, class: "fa fa-trash", data: { confirm: 'Are you sure?' } %></li>
    </ul>
  <% end %>
  <br />
  <div class="blog_post_contents">
    <%= post.generate_markdown_html.html_safe %>
  </div>
</div>

app/views/posts/_post.html.erb
<% title post.title %>

<div class="post">
  <div class="post-title"><h2><%= post.title %></h2></div>
  <div class="post-tags">
    <% post.tags.sort_by(&:name).each do |tag| %>
      <div class="post-tag">
        <%= link_to tag.name, posts_path(tag: tag.name) %>
      </div>
    <% end %>
  </div>
  <div class="post-date"><%= post.date_line %></div>
  <div class="post-buttons"></div>
    <% if authenticated? %>
      <%= link_to '', edit_post_url(post), class: "fa fa-pencil" %>
      <%= link_to '', post_url(post), method: :delete, class: "fa fa-trash", data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>

  <div class="post-content">
    <%= post.generate_markdown_html.html_safe %>
  </div>
</div>

<script type="text/javascript">
  document.addEventListener("turbolinks:load", () => {
    PR.prettyPrint();
  });
</script>

app/views/posts/archive.html.erb
<h2>Post Archive</h2>

<table id="post-archive" class="border-collapse">
  <thead>
    <td>Pub</td>
    <td>Title</td>
    <td>Created</td>
    <td>Updated</td>
  </thead>

  <% @posts.each do |post| %>
    <tr>
      <td style="text-align: center;"><%= post.published ? '✓' : '' %></td>
      <td><%= link_to post.title, post_url(post) %></td>
      <td><%= post.created_at.localtime.strftime('%m/%d/%y') %></td>
      <td><%= post.updated_at.localtime.strftime('%m/%d/%y') %></td>
    </tr>
  <% end %>
</table>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>
<div class="w-full">
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% title 'Blog' %>

<% if @tag %>
  <div class="post-tag-header">
    Viewing posts tagged '<%= @tag %>'
  </div>
  <div class="post-separator"></div>
<% end %>

<div id="post-index">
  <% @posts.each do |post| %>
    <div class="post-index-entry">
      <div class="post-index-entry-left">
        <% if post.image.attached? %>
          <%= image_tag url_for(post.image.variant(resize: '400x400')) if post.image.attached? %>
        <% else %>
          <%= image_tag 'logo-768', style: 'opacity: 0.1; margin-top: -0.1rem;' %>
        <% end %>
      </div>
      <div class="post-index-entry-right">
        <h2><%= link_to post.title, post_url(post) %></h2>
        <div class="post-index-entry-date"><%= post.date_line %></div>
      </div>
    </div>
  <% end %>
</div>

<div id="post-pages">
  <%= paginate @posts %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<div id="portfolio">
  <% @projects.each do |project| %>
    <div class="portfolio-entry">
      <div class="portfolio-entry-image">
        <%= image_tag url_for(project.image) %>
      </div>
      <div class="portfolio-entry-text">
        <% if project.url.present? %>
          <h3><%= link_to project.name, project.url %></h3>
        <% else %>
          <h3><%= project.name %></h3>
        <% end %>
        <p><%= project.description.html_safe %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>